Repository pajzo/myuplink, pull requests merged in 2024-02, with the labels that each got.

#13 Notifcation status as enum
  examples/example2.py
  src/myuplink/models.py
Labels: enhancement

#14 Device connection state enum
  examples/example1.py
  src/myuplink/models.py
Labels: enhancement

#15 MyUplinkAPI now using AbstractAuth
  setup.cfg
  src/myuplink/api.py
Labels: bug

#20 Add setter to DevicePoint.value and improve typing
  src/myuplink/models.py
Labels: enhancement

#21 Preparing for GitVersion setup
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  GitVersion.yml
  setup.cfg
Labels: enhancement

#22 Add PyPI link to readme
  README.md
Labels: documentation

#23 Walk-through of Models
  src/myuplink/__init__.py
  src/myuplink/api.py
  src/myuplink/models.py
Labels: enhancement

#25 Return valid enum or None
  src/myuplink/models.py
Labels: enhancement

#26 Processing with ruff and pylint, mostly docstrings
  src/myuplink/api.py
  src/myuplink/models.py
Labels: enhancement

#27 Change from List to generic list
  setup.cfg
  src/myuplink/api.py
  src/myuplink/models.py
Labels: enhancement

#28 Add calls for getting smart-home-modes and -zones from devices
  examples/example_zones.py
  src/myuplink/api.py
  src/myuplink/models.py
Labels: enhancement

#30 Add methods to get system names, models, etc
  examples/example_get_names.py
  src/myuplink/__init__.py
  src/myuplink/names.py
Labels: enhancement

#31 NamesAndReleaseTyping
  examples/example_enum_values.py
  examples/example_get_names.py
  examples/example_zones.py
  examples/my_token.py
  src/myuplink/__init__.py
  src/myuplink/models.py
  src/myuplink/names.py
Labels: enhancement

#32 Add some imports to __init__
  src/myuplink/__init__.py
Labels: enhancement
